development:
  adapter: postgresql
  encoding: unicode
  database: surveys_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: surveys_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: surveys_production
  pool: 5
